### ISSUE TITLE
Bad practices and anti-patterns

### ISSUE THREAD

**Issue by cyyynthia** [lorencerri/powercord-plugin-template#1]
Hello, Powercord developer here,

I appreciate the effort of making a template for new plugin developers. However, the template has some issues and may result in widespread pollution if not corrected.

 - [Invalid `shorthand` manifest key](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/manifest.json#L3)
There should be no additional manifest keys, as they may end up clashing with future versions of Powercord. Moreover, the use of this additional key is improper; more on that later

 - [Direct require of the manifest](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/index.js#L9)
This should be avoided as there's a better and safer way of accessing the manifest data, especially in the main plugin class.

 - [Declaration of the settings category](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/index.js#L21)
The `shorthand` use here is useless; It can safely be replaced by `this.entityID` which will in most cases be the same as what developers set `shorthand` to.

 - [Manifest-based label name](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/index.js#L23)
Although I have nothing against this practice (and in fact it's a rather smart approach), it can be replaced with `this.manifest.name` (see the previous point about requiring manifest).

 - [Bad injection ID practice](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/index.js#L45)
It's very likely plugins will do multiple injections, and they should explicitly set the injection ID everytime. It's better to ensure there's no surprise conflicts later on for beginners.

 - [Severe React antipatterns](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/Components/Settings.jsx#L12)
Props should **never** be saved like this. If the functions were to change for any reason (including but not limited to  context-changes in our own logic), the component will not be aware of those changes and will use the previous functions which can lead to, in the best case weird behaviors, in the worst case a hard crash or partial corruption of settings. **Always** access those methods using `this.props.getSetting`. If you are lazy, what you can do is **at the beginning of `render`**, save a shorthand. This way if a re-render occurs the functions used will be the expected ones.
```js
render () {
  const { getSetting, updateSetting, toggleSetting } = this.props;
```

 - [Minor misuse of `toggleSetting`](https://github.com/TrueXPixels/powercord-plugin-template/blob/master/Components/Settings.jsx#L27)
When the default value for a boolean setting is `true`, you should pass `true` as a 2nd argument of `toggleSetting`, otherwise when clicking it for the first time nothing will happen (as the toggler will think the default value is `false`, and pass it to `true`).

Those anti-patterns are not to take lightly as they might confuse beginners and people learning how to make Powercord plugins, and will even affect their general React knowledge which will be an issue even outside of the Powercord scope.

**Comment by lorencerri** [comment]
Hello, 

Thank you for taking the time to send feedback, I've fixed everything you've noted above in this repo (bb7077b) as well as in my other plugins. If there's anything else I should change, please let me know. I appreciate all the work you've done with Powercord and wish you all the best in the future. 

Have a wonderful day!
